<section class="section">
  <header class="k_section__header">Basic</header>
  <div class="row">
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="activity" class="br--round bg--yellow">activity</i><div class="fs--xs">activity</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="airplay">airplay</i><div class="fs--xs">airplay</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="alert-circle">alert-circle</i><div class="fs--xs">alert-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="alert-octagon">alert-octagon</i><div class="fs--xs">alert-octagon</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="alert-triangle">alert-triangle</i><div class="fs--xs">alert-triangle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="align-center">align-center</i><div class="fs--xs">align-center</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="align-justify">align-justify</i><div class="fs--xs">align-justify</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="align-left">align-left</i><div class="fs--xs">align-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="align-right">align-right</i><div class="fs--xs">align-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="anchor">anchor</i><div class="fs--xs">anchor</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="aperture">aperture</i><div class="fs--xs">aperture</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="archive" class="br--round bg--yellow">archive</i><div class="fs--xs">archive</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-down-circle">arrow-down-circle</i><div class="fs--xs">arrow-down-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-down-left">arrow-down-left</i><div class="fs--xs">arrow-down-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-down-right">arrow-down-right</i><div class="fs--xs">arrow-down-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-down">arrow-down</i><div class="fs--xs">arrow-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-left-circle">arrow-left-circle</i><div class="fs--xs">arrow-left-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-left">arrow-left</i><div class="fs--xs">arrow-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-right-circle">arrow-right-circle</i><div class="fs--xs">arrow-right-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-right">arrow-right</i><div class="fs--xs">arrow-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-up-circle">arrow-up-circle</i><div class="fs--xs">arrow-up-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-up-left">arrow-up-left</i><div class="fs--xs">arrow-up-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-up-right" class="br--round bg--yellow">arrow-up-right</i><div class="fs--xs">arrow-up-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="arrow-up">arrow-up</i><div class="fs--xs">arrow-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="at-sign">at-sign</i><div class="fs--xs">at-sign</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="award">award</i><div class="fs--xs">award</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bar-chart-2">bar-chart-2</i><div class="fs--xs">bar-chart-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bar-chart">bar-chart</i><div class="fs--xs">bar-chart</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="battery-charging">battery-charging</i><div class="fs--xs">battery-charging</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="battery">battery</i><div class="fs--xs">battery</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bell-off">bell-off</i><div class="fs--xs">bell-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bell">bell</i><div class="fs--xs">bell</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bluetooth">bluetooth</i><div class="fs--xs">bluetooth</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bold" class="br--round bg--yellow">bold</i><div class="fs--xs">bold</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="book-open">book-open</i><div class="fs--xs">book-open</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="book">book</i><div class="fs--xs">book</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="bookmark">bookmark</i><div class="fs--xs">bookmark</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="box">box</i><div class="fs--xs">box</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="briefcase">briefcase</i><div class="fs--xs">briefcase</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="calendar">calendar</i><div class="fs--xs">calendar</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="camera-off">camera-off</i><div class="fs--xs">camera-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="camera">camera</i><div class="fs--xs">camera</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cast">cast</i><div class="fs--xs">cast</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="check-circle">check-circle</i><div class="fs--xs">check-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="check-square" class="br--round bg--yellow">check-square</i><div class="fs--xs">check-square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="check">check</i><div class="fs--xs">check</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevron-down">chevron-down</i><div class="fs--xs">chevron-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevron-left">chevron-left</i><div class="fs--xs">chevron-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevron-right">chevron-right</i><div class="fs--xs">chevron-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevron-up">chevron-up</i><div class="fs--xs">chevron-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevrons-down">chevrons-down</i><div class="fs--xs">chevrons-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevrons-left">chevrons-left</i><div class="fs--xs">chevrons-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevrons-right">chevrons-right</i><div class="fs--xs">chevrons-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chevrons-up">chevrons-up</i><div class="fs--xs">chevrons-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="chrome">chrome</i><div class="fs--xs">chrome</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="circle" class="br--round bg--yellow">circle</i><div class="fs--xs">circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="clipboard">clipboard</i><div class="fs--xs">clipboard</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="clock">clock</i><div class="fs--xs">clock</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud-drizzle">cloud-drizzle</i><div class="fs--xs">cloud-drizzle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud-lightning">cloud-lightning</i><div class="fs--xs">cloud-lightning</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud-off">cloud-off</i><div class="fs--xs">cloud-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud-rain">cloud-rain</i><div class="fs--xs">cloud-rain</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud-snow">cloud-snow</i><div class="fs--xs">cloud-snow</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cloud">cloud</i><div class="fs--xs">cloud</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="code">code</i><div class="fs--xs">code</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="codepen">codepen</i><div class="fs--xs">codepen</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="command" class="br--round bg--yellow">command</i><div class="fs--xs">command</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="compass">compass</i><div class="fs--xs">compass</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="copy">copy</i><div class="fs--xs">copy</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-down-left">corner-down-left</i><div class="fs--xs">corner-down-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-down-right">corner-down-right</i><div class="fs--xs">corner-down-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-left-down">corner-left-down</i><div class="fs--xs">corner-left-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-left-up">corner-left-up</i><div class="fs--xs">corner-left-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-right-down">corner-right-down</i><div class="fs--xs">corner-right-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-right-up">corner-right-up</i><div class="fs--xs">corner-right-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-up-left">corner-up-left</i><div class="fs--xs">corner-up-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="corner-up-right">corner-up-right</i><div class="fs--xs">corner-up-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="cpu" class="br--round bg--yellow">cpu</i><div class="fs--xs">cpu</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="credit-card">credit-card</i><div class="fs--xs">credit-card</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="crop">crop</i><div class="fs--xs">crop</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="crosshair">crosshair</i><div class="fs--xs">crosshair</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="database">database</i><div class="fs--xs">database</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="delete">delete</i><div class="fs--xs">delete</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="disc">disc</i><div class="fs--xs">disc</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="dollar-sign">dollar-sign</i><div class="fs--xs">dollar-sign</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="download-cloud">download-cloud</i><div class="fs--xs">download-cloud</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="download">download</i><div class="fs--xs">download</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="droplet">droplet</i><div class="fs--xs">droplet</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="edit-2">edit-2</i><div class="fs--xs">edit-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="edit-3">edit-3</i><div class="fs--xs">edit-3</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="edit">edit</i><div class="fs--xs">edit</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="external-link">external-link</i><div class="fs--xs">external-link</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="eye-off">eye-off</i><div class="fs--xs">eye-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="eye">eye</i><div class="fs--xs">eye</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="facebook">facebook</i><div class="fs--xs">facebook</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="fast-forward">fast-forward</i><div class="fs--xs">fast-forward</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="feather">feather</i><div class="fs--xs">feather</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="file-minus">file-minus</i><div class="fs--xs">file-minus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="file-plus">file-plus</i><div class="fs--xs">file-plus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="file-text">file-text</i><div class="fs--xs">file-text</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="file">file</i><div class="fs--xs">file</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="film">film</i><div class="fs--xs">film</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="filter">filter</i><div class="fs--xs">filter</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="flag">flag</i><div class="fs--xs">flag</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="folder-minus">folder-minus</i><div class="fs--xs">folder-minus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="folder-plus">folder-plus</i><div class="fs--xs">folder-plus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="folder">folder</i><div class="fs--xs">folder</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="gift">gift</i><div class="fs--xs">gift</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="git-branch">git-branch</i><div class="fs--xs">git-branch</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="git-commit">git-commit</i><div class="fs--xs">git-commit</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="git-merge">git-merge</i><div class="fs--xs">git-merge</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="git-pull-request">git-pull-request</i><div class="fs--xs">git-pull-request</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="github">github</i><div class="fs--xs">github</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="gitlab">gitlab</i><div class="fs--xs">gitlab</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="globe">globe</i><div class="fs--xs">globe</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="grid">grid</i><div class="fs--xs">grid</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="hard-drive">hard-drive</i><div class="fs--xs">hard-drive</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="hash">hash</i><div class="fs--xs">hash</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="headphones">headphones</i><div class="fs--xs">headphones</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="heart">heart</i><div class="fs--xs">heart</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="help-circle">help-circle</i><div class="fs--xs">help-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="home">home</i><div class="fs--xs">home</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="image">image</i><div class="fs--xs">image</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="inbox">inbox</i><div class="fs--xs">inbox</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="info">info</i><div class="fs--xs">info</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="instagram">instagram</i><div class="fs--xs">instagram</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="italic">italic</i><div class="fs--xs">italic</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="layers">layers</i><div class="fs--xs">layers</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="layout">layout</i><div class="fs--xs">layout</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="life-buoy">life-buoy</i><div class="fs--xs">life-buoy</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="link-2">link-2</i><div class="fs--xs">link-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="link">link</i><div class="fs--xs">link</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="linkedin">linkedin</i><div class="fs--xs">linkedin</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="list">list</i><div class="fs--xs">list</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="loader">loader</i><div class="fs--xs">loader</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="lock">lock</i><div class="fs--xs">lock</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="log-in">log-in</i><div class="fs--xs">log-in</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="log-out">log-out</i><div class="fs--xs">log-out</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="mail">mail</i><div class="fs--xs">mail</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="map-pin">map-pin</i><div class="fs--xs">map-pin</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="map">map</i><div class="fs--xs">map</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="maximize-2">maximize-2</i><div class="fs--xs">maximize-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="maximize">maximize</i><div class="fs--xs">maximize</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="menu">menu</i><div class="fs--xs">menu</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="message-circle">message-circle</i><div class="fs--xs">message-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="message-square">message-square</i><div class="fs--xs">message-square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="mic-off">mic-off</i><div class="fs--xs">mic-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="mic">mic</i><div class="fs--xs">mic</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="minimize-2">minimize-2</i><div class="fs--xs">minimize-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="minimize">minimize</i><div class="fs--xs">minimize</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="minus-circle">minus-circle</i><div class="fs--xs">minus-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="minus-square">minus-square</i><div class="fs--xs">minus-square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="minus">minus</i><div class="fs--xs">minus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="monitor">monitor</i><div class="fs--xs">monitor</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="moon">moon</i><div class="fs--xs">moon</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="more-horizontal">more-horizontal</i><div class="fs--xs">more-horizontal</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="more-vertical">more-vertical</i><div class="fs--xs">more-vertical</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="move">move</i><div class="fs--xs">move</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="music">music</i><div class="fs--xs">music</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="navigation-2">navigation-2</i><div class="fs--xs">navigation-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="navigation">navigation</i><div class="fs--xs">navigation</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="octagon">octagon</i><div class="fs--xs">octagon</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="package">package</i><div class="fs--xs">package</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="paperclip">paperclip</i><div class="fs--xs">paperclip</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="pause-circle">pause-circle</i><div class="fs--xs">pause-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="pause">pause</i><div class="fs--xs">pause</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="percent">percent</i><div class="fs--xs">percent</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-call">phone-call</i><div class="fs--xs">phone-call</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-forwarded">phone-forwarded</i><div class="fs--xs">phone-forwarded</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-incoming">phone-incoming</i><div class="fs--xs">phone-incoming</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-missed">phone-missed</i><div class="fs--xs">phone-missed</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-off">phone-off</i><div class="fs--xs">phone-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone-outgoing">phone-outgoing</i><div class="fs--xs">phone-outgoing</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="phone">phone</i><div class="fs--xs">phone</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="pie-chart">pie-chart</i><div class="fs--xs">pie-chart</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="play-circle">play-circle</i><div class="fs--xs">play-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="play">play</i><div class="fs--xs">play</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="plus-circle">plus-circle</i><div class="fs--xs">plus-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="plus-square">plus-square</i><div class="fs--xs">plus-square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="plus">plus</i><div class="fs--xs">plus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="pocket">pocket</i><div class="fs--xs">pocket</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="power">power</i><div class="fs--xs">power</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="printer">printer</i><div class="fs--xs">printer</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="radio">radio</i><div class="fs--xs">radio</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="refresh-ccw">refresh-ccw</i><div class="fs--xs">refresh-ccw</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="refresh-cw">refresh-cw</i><div class="fs--xs">refresh-cw</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="repeat">repeat</i><div class="fs--xs">repeat</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="rewind">rewind</i><div class="fs--xs">rewind</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="rotate-ccw">rotate-ccw</i><div class="fs--xs">rotate-ccw</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="rotate-cw">rotate-cw</i><div class="fs--xs">rotate-cw</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="rss">rss</i><div class="fs--xs">rss</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="save">save</i><div class="fs--xs">save</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="scissors">scissors</i><div class="fs--xs">scissors</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="search">search</i><div class="fs--xs">search</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="send">send</i><div class="fs--xs">send</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="server">server</i><div class="fs--xs">server</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="settings">settings</i><div class="fs--xs">settings</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="share-2">share-2</i><div class="fs--xs">share-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="share">share</i><div class="fs--xs">share</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="shield-off">shield-off</i><div class="fs--xs">shield-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="shield">shield</i><div class="fs--xs">shield</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="shopping-bag">shopping-bag</i><div class="fs--xs">shopping-bag</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="shopping-cart">shopping-cart</i><div class="fs--xs">shopping-cart</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="shuffle">shuffle</i><div class="fs--xs">shuffle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="sidebar">sidebar</i><div class="fs--xs">sidebar</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="skip-back">skip-back</i><div class="fs--xs">skip-back</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="skip-forward">skip-forward</i><div class="fs--xs">skip-forward</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="slack">slack</i><div class="fs--xs">slack</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="slash">slash</i><div class="fs--xs">slash</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="sliders">sliders</i><div class="fs--xs">sliders</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="smartphone">smartphone</i><div class="fs--xs">smartphone</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="speaker">speaker</i><div class="fs--xs">speaker</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="square">square</i><div class="fs--xs">square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="star">star</i><div class="fs--xs">star</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="stop-circle">stop-circle</i><div class="fs--xs">stop-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="sun">sun</i><div class="fs--xs">sun</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="sunrise">sunrise</i><div class="fs--xs">sunrise</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="sunset">sunset</i><div class="fs--xs">sunset</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="tablet">tablet</i><div class="fs--xs">tablet</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="tag">tag</i><div class="fs--xs">tag</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="target">target</i><div class="fs--xs">target</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="terminal">terminal</i><div class="fs--xs">terminal</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="thermometer">thermometer</i><div class="fs--xs">thermometer</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="thumbs-down">thumbs-down</i><div class="fs--xs">thumbs-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="thumbs-up">thumbs-up</i><div class="fs--xs">thumbs-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="toggle-left">toggle-left</i><div class="fs--xs">toggle-left</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="toggle-right">toggle-right</i><div class="fs--xs">toggle-right</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="trash-2">trash-2</i><div class="fs--xs">trash-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="trash">trash</i><div class="fs--xs">trash</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="trending-down">trending-down</i><div class="fs--xs">trending-down</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="trending-up">trending-up</i><div class="fs--xs">trending-up</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="triangle">triangle</i><div class="fs--xs">triangle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="truck">truck</i><div class="fs--xs">truck</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="tv">tv</i><div class="fs--xs">tv</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="twitter">twitter</i><div class="fs--xs">twitter</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="type">type</i><div class="fs--xs">type</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="umbrella">umbrella</i><div class="fs--xs">umbrella</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="underline">underline</i><div class="fs--xs">underline</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="unlock">unlock</i><div class="fs--xs">unlock</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="upload-cloud">upload-cloud</i><div class="fs--xs">upload-cloud</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="upload">upload</i><div class="fs--xs">upload</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="user-check">user-check</i><div class="fs--xs">user-check</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="user-minus">user-minus</i><div class="fs--xs">user-minus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="user-plus">user-plus</i><div class="fs--xs">user-plus</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="user-x">user-x</i><div class="fs--xs">user-x</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="user">user</i><div class="fs--xs">user</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="users">users</i><div class="fs--xs">users</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="video-off">video-off</i><div class="fs--xs">video-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="video">video</i><div class="fs--xs">video</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="voicemail">voicemail</i><div class="fs--xs">voicemail</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="volume-1">volume-1</i><div class="fs--xs">volume-1</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="volume-2">volume-2</i><div class="fs--xs">volume-2</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="volume-x">volume-x</i><div class="fs--xs">volume-x</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="volume">volume</i><div class="fs--xs">volume</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="watch">watch</i><div class="fs--xs">watch</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="wifi-off">wifi-off</i><div class="fs--xs">wifi-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="wifi">wifi</i><div class="fs--xs">wifi</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="wind">wind</i><div class="fs--xs">wind</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="x-circle">x-circle</i><div class="fs--xs">x-circle</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="x-square">x-square</i><div class="fs--xs">x-square</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="x">x</i><div class="fs--xs">x</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="youtube">youtube</i><div class="fs--xs">youtube</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="zap-off">zap-off</i><div class="fs--xs">zap-off</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="zap">zap</i><div class="fs--xs">zap</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="zoom-in">zoom-in</i><div class="fs--xs">zoom-in</div></div>
    <div class="col w--1/3 w--1/6@t w--10@d flex--middle mb--2"><i data-feather="zoom-out">zoom-out</i><div class="fs--xs">zoom-out</div></div>

  </div>
</section>
